// AUTOGENERATED by frontend/scripts/sync-data-sources.mjs — do not edit.
import type { SourceEntry } from "./SourceRegistry";

export const SOURCES: Record<string, SourceEntry> = {
  "derived-agenda": {
    "id": "derived-agenda",
    "name": "Härledd agenda (per koalition)",
    "kind": "synthesized",
    "upstream": null,
    "license": null,
    "freshness": "deterministisk (rendrar samma resultat för samma input)",
    "lastVerified": "Fri May 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "Vi har ingen primärkälla i Sverige som publicerar regeringens / regionstyrets / kommunstyrets faktiska årsplan i strukturerad form. Vi **genererar** därför en agenda från koalitionens partisammansättning."
  },
  "kolada-spending": {
    "id": "kolada-spending",
    "name": "Kolada — kommunal verksamhetsutgift",
    "kind": "api",
    "upstream": "https://api.kolada.se/v3",
    "license": "Kommun- och regionkollade — fri användning",
    "freshness": "årlig",
    "lastVerified": "Fri May 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "Samma upstream som [kolada](./kolada.md), men begränsad till de KPI-id:n som beskriver kommunens verksamhetsutgifter per ansvarsområde — skola, omsorg, plan, gata, etc. Separata MD eftersom endpointen, mappningen, och visualiseringen skiljer sig från KPI-stripen."
  },
  "kolada": {
    "id": "kolada",
    "name": "Kolada API v3",
    "kind": "api",
    "upstream": "https://api.kolada.se/v3",
    "license": "Kommun- och regionkollade — fri användning",
    "freshness": "årlig",
    "lastVerified": "Fri May 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "Kolada är Rådet för främjande av kommunala analyser (RKA) sin databas med jämförelsetal för svenska kommuner och regioner — ekonomi, vård, skola, befolkning. Vi använder underlag för KPI-stripen på region- och kommunsidor."
  },
  "riksdagen": {
    "id": "riksdagen",
    "name": "Riksdagen Open Data",
    "kind": "api",
    "upstream": "https://data.riksdagen.se",
    "license": "Public domain — Sveriges riksdag",
    "freshness": "dagligen (cron: politicians @daily, speeches @daily, votes @daily)",
    "lastVerified": "Fri May 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "Riksdagens öppna data är portalen som sveriges riksdag publicerar för all kammaraktivitet: ledamöter, anföranden, omröstningar, betänkanden, motioner och utskottsärenden. Det är primärkällan för all \"vad har politikerna gjort\" -data på sidan."
  },
  "scb-befolkning": {
    "id": "scb-befolkning",
    "name": "SCB BefolkningNy",
    "kind": "api",
    "upstream": "https://api.scb.se/OV0104/v1/doris/sv/ssd/BE/BE0101/BE0101A/BefolkningNy",
    "license": "PxWeb open data — fri användning",
    "freshness": "årlig (kvartal för kommunnivå)",
    "lastVerified": "Fri May 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "SCB:s folkmängdsdatabas — total befolkning per kommun."
  },
  "scb-kfmandat": {
    "id": "scb-kfmandat",
    "name": "SCB Kfmandat (kommunala mandat)",
    "kind": "api",
    "upstream": "https://api.scb.se/OV0104/v1/doris/sv/ssd/ME/ME0104/ME0104A/Kfmandat",
    "license": "PxWeb open data — fri användning",
    "freshness": "4-årscykel (val)",
    "lastVerified": "Fri May 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "SCB:s tabell över mandatfördelning i kommunfullmäktige efter senaste val. Källa till alla mandatkort på kommunsidor."
  },
  "scb-kostndrlt": {
    "id": "scb-kostndrlt",
    "name": "SCB KostnDRLT (regionernas driftkostnader)",
    "kind": "api",
    "upstream": "https://api.scb.se/OV0104/v1/doris/sv/ssd/OE/OE0107/OE0107D/KostnDRLT",
    "license": "PxWeb open data — fri användning",
    "freshness": "årlig",
    "lastVerified": "Fri May 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "SCB:s tabell över regioners nettokostnader per verksamhetsområde (hälso- och sjukvård, kollektivtrafik, regional utveckling)."
  },
  "scb-ltmandat": {
    "id": "scb-ltmandat",
    "name": "SCB Ltmandat (regionala mandat)",
    "kind": "api",
    "upstream": "https://api.scb.se/OV0104/v1/doris/sv/ssd/ME/ME0104/ME0104B/Ltmandat",
    "license": "PxWeb open data — fri användning",
    "freshness": "4-årscykel (val)",
    "lastVerified": "Fri May 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "SCB:s tabell över mandatfördelning i regionfullmäktige (landsting). Syster till Kfmandat men för regionnivå."
  },
  "seed-budget-data": {
    "id": "seed-budget-data",
    "name": "Statsbudget (seed)",
    "kind": "seed",
    "upstream": "https://www.regeringen.se/rattsliga-dokument/proposition/",
    "license": "Public domain — Regeringskansliet",
    "freshness": "engångs per år; uppdateras vid ny budget",
    "lastVerified": "Fri May 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "Hand-kuraterad data från statens budgetproposition (BP) över flera år. Innehåller anslagna belopp per utgiftsområde (UO 1–27) samt vilken status posten har — föreslagen av regeringen eller beslutad av riksdagen."
  },
  "seed-party-goals": {
    "id": "seed-party-goals",
    "name": "Partimål (seed)",
    "kind": "seed",
    "upstream": null,
    "license": "Sammanställt från partiernas valmanifest 2022",
    "freshness": "engångs (vid antagande); uppdateras manuellt vid nya manifest",
    "lastVerified": "Fri May 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "Hand-kuraterade mål från partiernas valmanifest 2022. Varje mål har en citation tillbaka till källtexten — vanligtvis en specifik sida i partiets PDF-manifest. På så sätt kan du för varje mål gå tillbaka och verifiera ordagrant vad partiet skrev i sitt manifest."
  },
  "statskontoret-arsutfall": {
    "id": "statskontoret-arsutfall",
    "name": "Statskontoret — Årsutfall för myndigheter",
    "kind": "csv",
    "upstream": "https://www.statskontoret.se/psidata/arsutfall",
    "license": "Statskontoret open data — fri användning",
    "freshness": "årlig",
    "lastVerified": "Fri May 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "Statskontoret publicerar årligen statliga myndigheters faktiska driftkostnader (löner, lokaler, IT — exkl. transfereringar) som en ZIP med CSV-filer. Detta är \"kvittot\" för Myndigheter-kortet på Riksdag-sidan."
  },
  "ted": {
    "id": "ted",
    "name": "TED — Tenders Electronic Daily",
    "kind": "api",
    "upstream": "https://ted.europa.eu/",
    "license": "EU public data",
    "freshness": "löpande",
    "lastVerified": "Fri May 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "EU:s officiella databas över alla offentliga upphandlingar över tröskelvärdet. Vi använder den för att visa kommunala kontrakt på kommunsidor."
  },
  "wikimedia-svg": {
    "id": "wikimedia-svg",
    "name": "Sverige-karta SVG (Wikimedia Commons)",
    "kind": "seed",
    "upstream": "https://commons.wikimedia.org/wiki/Category:Maps_of_municipalities_of_Sweden",
    "license": "CC BY-SA 2.5",
    "freshness": "engångs (statiska SVG-banor inkluderade i bundle)",
    "lastVerified": "Fri May 08 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "SVG-paths för Sveriges 21 regioner och 290 kommuner. De är inbyggda direkt i sidan så kartan kan ritas omedelbart utan extra hämtning. Ursprunget är Wikimedia Commons, baserat på SCB:s administrativa indelning."
  },
};

export type SourceId = keyof typeof SOURCES;
