// AUTOGENERATED by frontend/scripts/sync-data-sources.mjs — do not edit.
import type { SourceEntry } from "./SourceRegistry";

export const SOURCES: Record<string, SourceEntry> = {
  "derived-agenda": {
    "id": "derived-agenda",
    "name": "Härledd agenda (per koalition)",
    "kind": "synthesized",
    "upstream": null,
    "license": null,
    "freshness": "deterministisk (rendrar samma resultat för samma input)",
    "lastVerified": "Sat Jun 06 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "Vi har ingen primärkälla i Sverige som publicerar regeringens / regionstyrets / kommunstyrets faktiska årsplan i strukturerad form. Vi **genererar** därför en agenda från koalitionens partisammansättning.",
    "verificationStatus": "frozen",
    "verificationNotes": null
  },
  "kolada-spending": {
    "id": "kolada-spending",
    "name": "Kolada — kommunal verksamhetsutgift",
    "kind": "api",
    "upstream": "https://api.kolada.se/v3",
    "license": "Kommun- och regionkollade — fri användning",
    "freshness": "årlig",
    "lastVerified": "Sat Jun 06 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "Samma upstream som [kolada](./kolada.md), men begränsad till de KPI-id:n som beskriver kommunens verksamhetsutgifter per ansvarsområde — skola, omsorg, plan, gata, etc. Separata MD eftersom endpointen, mappningen, och visualiseringen skiljer sig från KPI-stripen.",
    "verificationStatus": "unsure",
    "verificationNotes": "Reproduktionsnarrativet innehöll ett curl-kommando (förbjudet i käll-MD); ersatt med prosaöversikt. Repro-narrativet är nu godkänt."
  },
  "kolada": {
    "id": "kolada",
    "name": "Kolada API v3",
    "kind": "api",
    "upstream": "https://api.kolada.se/v3",
    "license": "Kommun- och regionkollade — fri användning",
    "freshness": "årlig",
    "lastVerified": "Sat Jun 06 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "Kolada är Rådet för främjande av kommunala analyser (RKA) sin databas med jämförelsetal för svenska kommuner och regioner — ekonomi, vård, skola, befolkning. Vi använder underlag för KPI-stripen på region- och kommunsidor.",
    "verificationStatus": "unsure",
    "verificationNotes": "Reproduktionsnarrativet innehöll curl-kommandon (förbjudna i käll-MD); ersatta med prosaöversikt. Repro-narrativet är nu godkänt."
  },
  "riksdagen": {
    "id": "riksdagen",
    "name": "Riksdagen Open Data",
    "kind": "api",
    "upstream": "https://data.riksdagen.se",
    "license": "Public domain — Sveriges riksdag",
    "freshness": "dagligen (cron: politicians @daily, speeches @daily, votes @daily)",
    "lastVerified": "Sat Jun 06 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "Riksdagens öppna data är portalen som Sveriges riksdag publicerar för all kammaraktivitet: ledamöter, anföranden, omröstningar, betänkanden, motioner och utskottsärenden. Det är primärkällan för all \"vad har politikerna gjort\"-data på sidan.",
    "verificationStatus": "unsure",
    "verificationNotes": "Reproduktionsnarrativet innehöll tre curl-kommandon (förbjudna i käll-MD); ersatta med prosaöversikt. Repro-narrativet är nu godkänt."
  },
  "scb-befolkning": {
    "id": "scb-befolkning",
    "name": "SCB BefolkningNy",
    "kind": "api",
    "upstream": "https://api.scb.se/OV0104/v1/doris/sv/ssd/BE/BE0101/BE0101A/BefolkningNy",
    "license": "PxWeb open data — fri användning",
    "freshness": "årlig (kvartal för kommunnivå)",
    "lastVerified": "Sat Jun 06 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "SCB:s folkmängdsdatabas — total befolkning per kommun.",
    "verificationStatus": "unsure",
    "verificationNotes": "Reproduktionsnarrativet innehöll ett curl-kommando med POST-kropp (förbjudet i käll-MD); ersatt med prosaöversikt. Dessutom renderar MunicipalityDetailPage befolkningssiffran utan SourceMarker (se audit Appendix 1)."
  },
  "scb-kfmandat": {
    "id": "scb-kfmandat",
    "name": "SCB Kfmandat (kommunala mandat)",
    "kind": "api",
    "upstream": "https://api.scb.se/OV0104/v1/doris/sv/ssd/ME/ME0104/ME0104A/Kfmandat",
    "license": "PxWeb open data — fri användning",
    "freshness": "4-årscykel (val)",
    "lastVerified": "Sat Jun 06 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "SCB:s tabell över mandatfördelning i kommunfullmäktige efter senaste val. Källa till alla mandatkort på kommunsidor.",
    "verificationStatus": "unsure",
    "verificationNotes": "Reproduktionsnarrativet innehöll två curl-kommandon med POST-kropp (förbjudna i käll-MD); ersatta med prosaöversikt. Repro-narrativet är nu godkänt."
  },
  "scb-kls-headcount": {
    "id": "scb-kls-headcount",
    "name": "SCB KLS — Månadsanställda i statlig sektor (AM0102)",
    "kind": "api",
    "upstream": "https://www.scb.se/hitta-statistik/statistik-efter-amne/arbetsmarknad/loner-och-arbetskostnader/konjunkturstatistik-loner-for-statlig-sektor-kls/",
    "license": "SCB öppna data — fri användning (CC0)",
    "freshness": "månadsvis (december-snapshot används som årsavstämning)",
    "lastVerified": "Sat Jun 06 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "SCB:s Konjunkturstatistik löner, sysselsättning och arbetstid (KLS) är en månatlig enkät till statliga arbetsgivare om antal anställda. Vi använder Tabell 14 — *Månadsanställda i statlig sektor per myndighet* — ur databasdelen AM0102A. Varje post avser en specifik myndighet (kodad med KLS-myndighetskod) och ett specifikt månadsslut. Vi tar december-snapshoten för varje år och använder dem som årsavstämningar för att bygga personalhistorik.",
    "verificationStatus": "verified",
    "verificationNotes": null
  },
  "scb-kostndrlt": {
    "id": "scb-kostndrlt",
    "name": "SCB KostnDRLT (regionernas driftkostnader)",
    "kind": "api",
    "upstream": "https://api.scb.se/OV0104/v1/doris/sv/ssd/OE/OE0107/OE0107D/KostnDRLT",
    "license": "PxWeb open data — fri användning",
    "freshness": "årlig",
    "lastVerified": "Sat Jun 06 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "SCB:s tabell över regioners nettokostnader per verksamhetsområde (hälso- och sjukvård, kollektivtrafik, regional utveckling).",
    "verificationStatus": "unsure",
    "verificationNotes": "Reproduktionsnarrativet innehöll ett curl-kommando med POST-kropp (förbjudet i käll-MD); ersatt med prosaöversikt. Dessutom renderar RegionBudgetAreaPage mnkr-värden utan SourceMarker (se audit Appendix 1)."
  },
  "scb-ltmandat": {
    "id": "scb-ltmandat",
    "name": "SCB Ltmandat (regionala mandat)",
    "kind": "api",
    "upstream": "https://api.scb.se/OV0104/v1/doris/sv/ssd/ME/ME0104/ME0104B/Ltmandat",
    "license": "PxWeb open data — fri användning",
    "freshness": "4-årscykel (val)",
    "lastVerified": "Sat Jun 06 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "SCB:s tabell över mandatfördelning i regionfullmäktige (landsting). Syster till Kfmandat men för regionnivå.",
    "verificationStatus": "unsure",
    "verificationNotes": "Reproduktionsnarrativet innehöll ett curl-kommando med POST-kropp (förbjudet i käll-MD); ersatt med prosaöversikt. Repro-narrativet är nu godkänt."
  },
  "scb-myndighetsregistret": {
    "id": "scb-myndighetsregistret",
    "name": "SCB Myndighetsregistret",
    "kind": "api",
    "upstream": "https://myndighetsregistret.scb.se",
    "license": "SCB öppna data — fri användning",
    "freshness": "löpande (uppdateras när myndigheter inrättas, avvecklas eller byter namn)",
    "lastVerified": "Sat Jun 06 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "SCB:s Myndighetsregister är den officiella förteckningen över alla statliga myndigheter i Sverige. Det förs av Statistiska centralbyrån på uppdrag av regeringen och innehåller namn, organisationsnummer, typ (förvaltningsmyndighet, domstol, utlandsmyndighet m.m.), huvudman och webbadress för varje myndighet. Registret är källan för hela myndighetslistans struktur på sidan — utan det vet vi inte ens vilka myndigheter som existerar.",
    "verificationStatus": "verified",
    "verificationNotes": null
  },
  "seed-budget-data": {
    "id": "seed-budget-data",
    "name": "Statsbudget (seed)",
    "kind": "seed",
    "upstream": "https://www.regeringen.se/rattsliga-dokument/proposition/",
    "license": "Public domain — Regeringskansliet",
    "freshness": "engångs per år; uppdateras vid ny budget",
    "lastVerified": "Sat Jun 06 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "Hand-kuraterad data från statens budgetproposition (BP) över flera år. Innehåller anslagna belopp per utgiftsområde (UO 1–27) samt vilken status posten har — föreslagen av regeringen eller beslutad av riksdagen.",
    "verificationStatus": "frozen",
    "verificationNotes": null
  },
  "seed-party-goals": {
    "id": "seed-party-goals",
    "name": "Partimål (seed)",
    "kind": "seed",
    "upstream": null,
    "license": "Sammanställt från partiernas valmanifest 2022",
    "freshness": "engångs (vid antagande); uppdateras manuellt vid nya manifest",
    "lastVerified": "Sat Jun 06 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "Hand-kuraterade mål från partiernas valmanifest 2022. Varje mål har en citation tillbaka till källtexten — vanligtvis en specifik sida i partiets PDF-manifest. På så sätt kan du för varje mål gå tillbaka och verifiera ordagrant vad partiet skrev i sitt manifest.",
    "verificationStatus": "frozen",
    "verificationNotes": null
  },
  "statskontoret-arsutfall": {
    "id": "statskontoret-arsutfall",
    "name": "Statskontoret — Årsutfall för myndigheter",
    "kind": "csv",
    "upstream": "https://www.statskontoret.se/analys-och-statistik/oppna-data/arsutfall/",
    "license": "Statskontoret open data — fri användning",
    "freshness": "årlig",
    "lastVerified": "Sat Jun 06 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "Statskontoret publicerar årligen statliga myndigheters faktiska driftkostnader (löner, lokaler, IT — exkl. transfereringar) som en ZIP med CSV-filer. Detta är \"kvittot\" för Myndigheter-kortet på Riksdag-sidan.",
    "verificationStatus": "unsure",
    "verificationNotes": "Det dokumenterade upstream-URL:et /psidata/arsutfall returnerar 200 men den faktiska ZIP-filen hämtas via en dynamisk GetFile-länk som ändrats sedan MD skrevs; tidigare bash-block med curl/unzip borttaget. Dessutom saknar AuthorityDetailPage och MyndigheterListPage SourceMarker på kostnads- och personalvärden (se audit Appendix 1)."
  },
  "statskontoret-myndighetsforteckning": {
    "id": "statskontoret-myndighetsforteckning",
    "name": "Statskontoret — Myndighetsförteckning (årsarbetskrafter)",
    "kind": "csv",
    "upstream": "https://www.statskontoret.se/analys-och-statistik/oppna-data/myndighetsforteckning/",
    "license": "Statskontoret open data — fri användning",
    "freshness": "årlig (ny version publiceras vanligtvis under Q1 nästkommande år)",
    "lastVerified": "Sat Jun 06 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "Statskontoret publicerar varje år en Myndighetsförteckning — ett XLSX-dokument med longitudinella personaluppgifter för samtliga statliga myndigheter. Centrala måttet är *årsarbetskrafter*: heltidsekvivalenter per myndighet och år, med täckning från 2007 och framåt. Statskontoret beräknar detta mått från arbetsgivardeklarationer till Skatteverket och det är det officiella måttet för personalstyrka i statlig sektor.",
    "verificationStatus": "verified",
    "verificationNotes": "Den exakta XLSX-URL:en innehåller ett hårdkodat filnamn med årstal (statskontorets-myndighetsforteckning-2025.xlsx). URL:en måste uppdateras när Statskontoret publicerar nästa utgåva."
  },
  "ted": {
    "id": "ted",
    "name": "TED — Tenders Electronic Daily",
    "kind": "api",
    "upstream": "https://api.ted.europa.eu/v3/notices/search",
    "license": "EU public data",
    "freshness": "löpande",
    "lastVerified": "Sat Jun 06 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "EU:s officiella databas över alla offentliga upphandlingar över tröskelvärdet. Vi använder den för att visa kommunala kontrakt på kommunsidor.",
    "verificationStatus": "unsure",
    "verificationNotes": "Upstream-URL i MD pekade på ted.europa.eu (webbgränssnitt) men backenden anropar api.ted.europa.eu/v3/notices/search; MD uppdaterat till korrekt API-host. Tidigare bash-block med curl mot fel host borttaget. Inga SourceMarker-konsumenter finns i UI idag."
  },
  "wikimedia-svg": {
    "id": "wikimedia-svg",
    "name": "Sverige-karta SVG (Wikimedia Commons)",
    "kind": "seed",
    "upstream": "https://commons.wikimedia.org/wiki/Category:Maps_of_municipalities_of_Sweden",
    "license": "CC BY-SA 2.5",
    "freshness": "engångs (statiska SVG-banor inkluderade i bundle)",
    "lastVerified": "Sat Jun 06 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "blurb": "SVG-paths för Sveriges 21 regioner och 290 kommuner. De är inbyggda direkt i sidan så kartan kan ritas omedelbart utan extra hämtning. Ursprunget är Wikimedia Commons, baserat på SCB:s administrativa indelning.",
    "verificationStatus": "unsure",
    "verificationNotes": "CC BY-SA 2.5-licensen kräver synlig attribution i UI, men SourceMarker saknas på alla kart-vyer (SwedenRegionMap, SwedenKommunMap); attributionen är planerad som en del av Task 16 i verifieringsplanen."
  },
};

export type SourceId = keyof typeof SOURCES;
