export type SourceKind = "api" | "csv" | "seed" | "synthesized";

export interface SourceEntry {
  id: string;
  name: string;
  kind: SourceKind;
  upstream: string | null;
  license: string | null;
  freshness: string | null;
  lastVerified: string;
  blurb: string;
}

// Re-export the autogenerated map so call sites import from one place.
export { SOURCES, type SourceId } from "./SourceRegistry.generated";
