## Production overrides — merge on top of values.yaml
backend:
  replicas: 1
  image:
    repository: ghcr.io/runemark7/riksdagskollen-api
    pullPolicy: Always
    tag: a797cfde2f2dd483d63cf00e852c26b232cc6f7f
  imagePullSecrets:
    - name: ghcr-pull-secret
  env:
    CORS_ALLOWED_ORIGIN: "https://sdt.runevibe.se"
    SEED_ELECTIONS: "true"
frontend:
  replicas: 1
  image:
    repository: ghcr.io/runemark7/riksdagskollen-frontend
    pullPolicy: Always
    tag: a797cfde2f2dd483d63cf00e852c26b232cc6f7f
  imagePullSecrets:
    - name: ghcr-pull-secret
postgresql:
  enabled: false
ingress:
  host: sdt.runevibe.se
  tlsSecretName: sdt-runevibe-tls
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
