-- Region annual-plan documents + the regions' own overarching goals.
-- Every region must adopt a budget with goals/guidelines (Kommunallagen 11 kap.).
-- There is no structured national feed of these plans, so the goals are
-- transcribed verbatim and complete from each region's own decided document,
-- and we always link the original. Regions whose plan has no cleanly
-- extractable overarching set carry a plan row with the link but no goals.
-- Source registry id: region-budget-plan (see docs/data-sources/region-budget-plan.md).

CREATE TABLE region_plan (
    region_code TEXT        PRIMARY KEY REFERENCES regions(code) ON DELETE CASCADE,
    label       TEXT        NOT NULL,
    url         TEXT        NOT NULL,
    goals_label TEXT,
    period      TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE region_plan_goal (
    id          SERIAL  PRIMARY KEY,
    region_code TEXT    NOT NULL REFERENCES region_plan(region_code) ON DELETE CASCADE,
    sort_order  INTEGER NOT NULL,
    title       TEXT    NOT NULL,
    description TEXT,
    UNIQUE (region_code, sort_order)
);

CREATE INDEX ON region_plan_goal (region_code);

INSERT INTO region_plan (region_code, label, url, goals_label, period) VALUES
  ('01', 'Budget för Region Stockholm', 'https://www.regionstockholm.se/om-region-stockholm/ekonomi-och-budget/budget/', 'Mål i budget', '2026'),
  ('03', 'Regionplan och budget', 'https://regionuppsala.se/politik-och-paverkan/handlingar/styrande-dokument/', 'Strategiska mål', NULL),
  ('04', 'Mål och budget', 'https://regionsormland.se/om-region-sormland/ekonomi-och-budget/mal-budget/', 'Politiska målområden', '2025–2027'),
  ('05', 'Strategisk plan med treårsbudget', 'https://www.regionostergotland.se/ro/om-region-ostergotland/ekonomi/planering-och-uppfoljning', NULL, NULL),
  ('06', 'Budget med verksamhetsplan', 'https://www.rjl.se/om-oss/Budget-och-styrdokument/budget-med-verksamhetsplan-och-flerarsplan/', 'Strategiska mål', NULL),
  ('07', 'Budget (styrande dokument)', 'https://www.regionkronoberg.se/om-region-kronoberg/styrdokument/', NULL, NULL),
  ('08', 'Regionplan och budget', 'https://regionkalmar.se/politik-och-demokrati/styrande-dokument/mal-budget-och-uppfoljning/', NULL, NULL),
  ('09', 'Mål och budget', 'https://gotland.se/region-och-politik/regionfakta-och-statistik/ekonomi-budget-och-publikationer/region-gotlands-budget', NULL, NULL),
  ('10', 'Budget med flerårsplan', 'https://regionblekinge.se/om-region-blekinge/styrning-och-mal/budget-2025-med-planer-2026-2027.html', 'Övergripande mål', '2025'),
  ('12', 'Verksamhetsplan och budget', 'https://www.skane.se/om-region-skane/detta-gor-region-skane/publikationer/budget-2025/', NULL, NULL),
  ('13', 'Budget och ekonomi', 'https://www.regionhalland.se/om-region-halland/budget-och-ekonomi/', NULL, NULL),
  ('14', 'Budget', 'https://www.vgregion.se/politik/sa-styrs-vastra-gotalandsregionen/budget/', 'Mål i budget', '2026'),
  ('17', 'Regionplan och budget', 'https://www.regionvarmland.se/regionvarmland/om-regionen/om-region-varmland/styrande-dokument', 'Effektmål', '2025–2027'),
  ('18', 'Verksamhetsplan med budget', 'https://www.regionorebrolan.se/sv/organisation-och-politik/ekonomi-och-budget/budget/', 'Övergripande målsättningar', '2025'),
  ('19', 'Regionplan och budget', 'https://regionvastmanland.se/contentassets/8afcc008e2e04f3a86bc106b417915e5/reviderad-regionplan-och-budget-2026-2028.pdf', 'Regionfullmäktiges övergripande mål', '2026–2028'),
  ('20', 'Regionplan med budget', 'https://www.regiondalarna.se/om-oss/regionplan/', 'Målområden', '2025–2027'),
  ('21', 'Budget', 'https://www.regiongavleborg.se/om/ekonomi/', NULL, NULL),
  ('22', 'Regionplan', 'https://www.rvn.se/sv/Demokrati-och-insyn/Sa-styrs-regionen/Regionplanen/', 'Målområden', '2026–2028'),
  ('23', 'Regionplan och budget', 'https://www.regionjh.se/om-regionen/ekonomi-och-budget', 'Övergripande mål', '2025–2027'),
  ('24', 'Regionplan', 'https://www.regionvasterbotten.se/ekonomi-och-planering', 'Regionmål', '2024'),
  ('25', 'Strategisk plan med budget', 'https://www.norrbotten.se/sv/demokrati-och-politik/styrande-dokument/', NULL, NULL);

INSERT INTO region_plan_goal (region_code, sort_order, title, description) VALUES
  ('01', 1, 'Hälso- och sjukvården är behovsstyrd, jämlik och förebygger ohälsa', NULL),
  ('01', 2, 'Kollektivtrafiken är tillgänglig och attraktiv', NULL),
  ('01', 3, 'Den hållbara regionala utvecklingen ligger i framkant', NULL),
  ('01', 4, 'Verksamheten är långsiktigt hållbar och kostnadseffektiv', NULL),
  ('01', 5, 'Kompetensförsörjningen är långsiktig', NULL),
  ('03', 1, 'Attraktiv arbetsplats', NULL),
  ('03', 2, 'Hög tillgänglighet', NULL),
  ('03', 3, 'God kvalitet med ekonomi i balans', NULL),
  ('03', 4, 'Hållbar och konkurrenskraftig utveckling', NULL),
  ('04', 1, 'Region Sörmland har en jämlik, tillgänglig, kvalitativ och effektiv verksamhet', NULL),
  ('04', 2, 'Region Sörmland arbetar hälsofrämjande och förebyggande', NULL),
  ('04', 3, 'Region Sörmland använder sina resurser hållbart och effektivt', NULL),
  ('06', 1, 'Bästa platsen att växa upp, leva, verka och åldras på', NULL),
  ('06', 2, 'Enklare vardag för invånare och medarbetare', NULL),
  ('06', 3, 'Bästa möjliga kvalitet', NULL),
  ('06', 4, 'Bäst på att förbättra och förnya', NULL),
  ('06', 5, 'Långsiktigt hållbar och innovativ tillväxtregion', NULL),
  ('06', 6, 'Sveriges bästa offentliga arbetsgivare med Sveriges bästa arbetsplatser', NULL),
  ('06', 7, 'God och hållbar hushållning', NULL),
  ('10', 1, 'Ett Blekinge som växer med fler Blekingebor och god kompetensförsörjning', NULL),
  ('10', 2, 'En tillgänglig verksamhet med hög kvalitet', NULL),
  ('10', 3, 'En attraktiv arbetsgivare med medarbetare som trivs och utvecklas', NULL),
  ('10', 4, 'En ansvarsfull och resurseffektiv ekonomi med budget i balans', NULL),
  ('14', 1, 'Västra Götalandsregionen ska stärka sin beredskap och motståndskraft för att bättre kunna hantera samhällsstörningar, kriser och ett förändrat säkerhetsläge', NULL),
  ('14', 2, 'Vård ska ges jämlikt i Västra Götalandsregionen', NULL),
  ('14', 3, 'Sjukvårdens köer ska kortas och tillgängligheten ska öka', NULL),
  ('14', 4, 'Invånarnas psykiska hälsa ska förbättras och den psykiatriska vården ska stärkas', NULL),
  ('14', 5, 'Invånarna ska få en god vård på rätt vårdnivå', NULL),
  ('14', 6, 'Folkhälsan ska förbättras för invånarna genom mer hälsofrämjande och sjukdomsförebyggande arbete i bred samverkan', NULL),
  ('14', 7, 'Västra Götalandsregionen ska verka för en minskad miljö- och klimatpåverkan i Västra Götaland', NULL),
  ('14', 8, 'Stärka innovationskraften – för ett hållbart och konkurrenskraftigt näringsliv i framkant', NULL),
  ('14', 9, 'Bygga kompetens för bättre kompetensförsörjning och livslångt lärande', NULL),
  ('14', 10, 'Knyta samman Västra Götaland med hållbara resor och förbättrad tillgänglighet', NULL),
  ('14', 11, 'Ett fritt, rikt och starkt kulturliv i hela Västra Götaland', NULL),
  ('14', 12, 'Västra Götalandsregionen ska vara en ledande och attraktiv arbetsgivare med konkurrenskraftiga löner och ett hälsofrämjande ledarskap som grund', NULL),
  ('14', 13, 'Medarbetarnas arbetsmiljö ska förbättras', NULL),
  ('14', 14, 'Ökad måluppfyllelse för Västra Götalandsregionens hållbarhetsmål', NULL),
  ('17', 1, 'Trygga och nöjda invånare', NULL),
  ('17', 2, 'Attraktivt och hållbart Värmland', NULL),
  ('17', 3, 'God, jämlik och jämställd hälsa', NULL),
  ('17', 4, 'Hållbar organisation', NULL),
  ('18', 1, 'Hälso- och sjukvården är god, säker och jämlik', NULL),
  ('18', 2, 'Tandvården är god, säker och jämlik', NULL),
  ('18', 3, 'En hållbar och attraktiv kollektivtrafik', NULL),
  ('18', 4, 'Den hållbara regionala utvecklingen ligger i framkant', NULL),
  ('18', 5, 'Forskning och utbildning av hög kvalitet med internationell spets', NULL),
  ('18', 6, 'Digitala lösningar för en enklare vardag för invånare och medarbetare', NULL),
  ('18', 7, 'Ansvarsfulla verksamheter med höga ambitioner för hållbar utveckling', NULL),
  ('18', 8, 'Kompetensförsörjningen är långsiktig', NULL),
  ('18', 9, 'En långsiktig stark och hållbar ekonomi med finansiell god hushållning', NULL),
  ('19', 1, 'Nöjda och trygga invånare', 'Perspektiv: Invånare'),
  ('19', 2, 'Effektiva och ändamålsenliga tjänster av god kvalitet', 'Perspektiv: Tjänst/process'),
  ('19', 3, 'Engagerade medarbetare med rätt kompetens', 'Perspektiv: Medarbetare'),
  ('19', 4, 'Ekonomi i balans', 'Perspektiv: Ekonomi'),
  ('20', 1, 'Till nytta för Dalarnas invånare', NULL),
  ('20', 2, 'Ett gott medarbetarskap och ledarskap', NULL),
  ('20', 3, 'Hållbar utveckling', NULL),
  ('22', 1, 'Ett attraktivt Västernorrland med hållbar utveckling', NULL),
  ('22', 2, 'Region Västernorrland utvecklar arbetet för en god, jämlik och nära vård', NULL),
  ('22', 3, 'Vi skapar mervärde för befolkningen genom vår verksamhet', NULL),
  ('23', 1, 'God och nära vård i hela Jämtland Härjedalen', 'Målområde för hälso- och sjukvård'),
  ('23', 2, 'God och tillgänglig tandvård i hela Jämtland Härjedalen', 'Målområde för tandvård'),
  ('23', 3, 'Utvecklingskraft i hela Jämtland Härjedalen', 'Målområde för regionalt utvecklingsansvar'),
  ('23', 4, 'Tillgängligt kulturutbud i hela Jämtland Härjedalen', 'Målområde för kultur'),
  ('23', 5, 'Goda kommunikationer inom samt till och från Jämtland Härjedalen', 'Målområde för kollektivtrafik'),
  ('23', 6, 'Folkhögskolor med hög kvalitet', 'Målområde för folkhögskolor'),
  ('23', 7, 'Ändamålsenlig kompetens för effektivt stöd till verksamhet och utveckling', 'Målområde för stödverksamhet'),
  ('24', 1, 'Trygga uppväxtvillkor', NULL),
  ('24', 2, 'Goda levnadsvillkor', NULL),
  ('24', 3, 'Ett attraktivt och hållbart Västerbotten', NULL),
  ('24', 4, 'Tillgänglig vård med god kvalitet och kontinuitet', NULL),
  ('24', 5, 'Goda arbetsplatser och attraktiva arbetsgivare', NULL),
  ('24', 6, 'En hållbar miljö- och klimatregion', NULL),
  ('24', 7, 'Stärkt forskning, utbildning och innovation', NULL);
