/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/riksdag/authorities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State agencies with actual annual expenditure (driftkostnader) */
        get: operations["getRiksdagAuthorities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/riksdag/authorities/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated coverage of the authorities register */
        get: operations["getRiksdagAuthorityStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/riksdag/authorities/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Searchable/filterable list of all state agencies (from authorities table) */
        get: operations["listRiksdagMyndigheter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/riksdag/authorities/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single state agency detail including regleringsbrev link */
        get: operations["getRiksdagAuthority"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/party-meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all parties with metadata */
        get: operations["listPartyMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/party-meta/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get party metadata by code */
        get: operations["getPartyMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ministers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active ministers grouped by department */
        get: operations["listMinisters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ministers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get minister detail with proposals */
        get: operations["getMinister"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all parties with summary scorecard data */
        get: operations["listParties"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties/{party}/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all goals for a party with alignment percentages */
        get: operations["listPartyGoals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties/{party}/goals/{goalId}/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detailed vote breakdown for a specific party goal */
        get: operations["listGoalVotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/politicians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List politicians with summary statistics */
        get: operations["listPoliticians"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/politicians/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full politician profile */
        get: operations["getPolitician"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/politicians/{id}/promises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Promises extracted from speeches with vote match results */
        get: operations["listPoliticianPromises"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/politicians/{id}/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Voting record with proposal origin context */
        get: operations["listPoliticianVotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/votes/riksdag-feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent Riksdag betänkanden relevant to a given governance level */
        get: operations["getRiksdagFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/votes/{beteckning}/{punkt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full vote detail with proposal origin and all party positions */
        get: operations["getVoteDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{dokId}/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full Riksdagen document — body HTML + intressenter list */
        get: operations["getDocumentFull"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{dokId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Riksdagen document metadata (no body HTML) */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all available budget years with totals */
        get: operations["listBudgetYears"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/years/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full budget breakdown for a specific year */
        get: operations["getBudgetYear"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/years/{year}/compare/{compareYear}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Side-by-side comparison of two budget years with deltas */
        get: operations["compareBudgetYears"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all 27 expenditure areas */
        get: operations["listExpenditureAreas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/context/topic/{topic}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Budget and economic context for a political topic */
        get: operations["getTopicContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/areas/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time series of budget amounts for one expenditure area */
        get: operations["getAreaTimeSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all 21 Swedish regions with election results and governing parties */
        get: operations["listRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions/kpi/{kpiCode}/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All regions ranked by a single KPI (highest first) */
        get: operations["getRegionKPIRanking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions/{code}/kpi-ranks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rank of a region for each strip KPI */
        get: operations["getRegionKPIRanks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full region detail including election results per party */
        get: operations["getRegion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions/{code}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Region's official annual-plan document and its own overarching goals (verbatim) */
        get: operations["getRegionPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions/{code}/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Real budget breakdown for a region from SCB (nettokostnader by verksamhetsområde) */
        get: operations["getRegionBudget"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions/{code}/budget/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Multi-year budget history for a region */
        get: operations["getRegionBudgetHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions/budget/area/{areaName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Budget data for one area across all regions */
        get: operations["getRegionAreaAcrossRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/municipalities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Swedish municipalities, optionally filtered by region */
        get: operations["listMunicipalities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/municipalities/kpi/{kpiCode}/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All municipalities ranked by a single KPI (highest first) */
        get: operations["getMunicipalityKPIRanking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/municipalities/{code}/kpi-ranks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rank of a municipality for each default KPI */
        get: operations["getMunicipalityKPIRanks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/municipalities/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full municipality detail including election results per party */
        get: operations["getMunicipality"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/municipalities/{code}/kpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kolada KPI spending metrics for a municipality */
        get: operations["getMunicipalityKPIs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/municipalities/{code}/spending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sector spending breakdown from Kolada (2019–2023) */
        get: operations["getMunicipalitySpending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/municipalities/{code}/budget/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Multi-year budget history for a municipality */
        get: operations["getMunicipalityBudgetHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/municipalities/{code}/procurement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public procurement breakdown by CPV category from TED (2021–2024) */
        get: operations["getMunicipalityProcurement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/municipalities/{code}/population-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SCB population trend for a municipality (2019–2023) */
        get: operations["getMunicipalityPopulationTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speeches/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent speeches across all politicians */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of recent speeches */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Speech"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speeches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single speech by id (full text) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Full speech detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Speech"];
                    };
                };
                /** @description Speech not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speeches/by-document/{dokId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Speeches whose rel_dok_id matches a betänkande */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dokId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of speeches in chronological debate order */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Speech"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speeches/by-politician/{intressentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent speeches by one politician */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path: {
                    intressentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Speeches by one politician, newest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Speech"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speeches/by-party/{party}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent speeches by all members of one party */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path: {
                    party: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Speeches by party members, newest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Speech"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/committees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Committees that decided at least one votering in a mandate period */
        get: operations["listCommittees"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/committees/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One committee with the utgiftsområden it bereder */
        get: operations["getCommittee"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            version?: string;
        };
        ErrorResponse: {
            error: string;
            detail?: string;
        };
        /**
         * @description Swedish party abbreviation
         * @enum {string}
         */
        PartyCode: "S" | "M" | "SD" | "C" | "V" | "KD" | "L" | "MP" | "unknown";
        /** @enum {string} */
        Topic: "sjukvard" | "forsvar" | "invandring" | "skatt" | "skola" | "klimat" | "brott" | "bostad" | "arbete" | "energi" | "pension" | "other";
        /** @enum {string} */
        VoteResult: "Ja" | "Nej" | "Avstår" | "Frånvarande";
        /**
         * @description prop=government bill, mot=party motion, bet=committee report
         * @enum {string}
         */
        ProposalType: "prop" | "mot" | "bet";
        /** @enum {string} */
        Specificity: "concrete" | "directional" | "rhetorical";
        Politician: {
            intressentId: string;
            firstName: string;
            lastName: string;
            party: components["schemas"]["PartyCode"];
            constituency?: string;
            /** Format: uri */
            imageUrl?: string;
            isActive: boolean;
        };
        PoliticianSummary: components["schemas"]["Politician"] & {
            totalVotes?: number;
            promiseCount?: number;
            /**
             * Format: float
             * @description Overall promise-to-vote alignment percentage
             */
            alignmentPct?: number;
        };
        PoliticianProfile: components["schemas"]["PoliticianSummary"] & {
            recentSpeeches?: components["schemas"]["SpeechSummary"][];
        };
        PoliticianListResponse: {
            data: components["schemas"]["PoliticianSummary"][];
            total: number;
            page: number;
            pageSize: number;
        };
        SpeechSummary: {
            id: number;
            dokId?: string;
            /** Format: date */
            date: string;
            topicHeading: string;
        };
        Vote: {
            id: number;
            voteringId: string;
            politicianId: string;
            party: components["schemas"]["PartyCode"];
            voteResult: components["schemas"]["VoteResult"];
            /** @description Committee report ID e.g. SoU12 */
            beteckning: string;
            forslagspunkt: string;
            /** @example 2024/25 */
            session: string;
            dokId?: string;
            proposedByParty?: components["schemas"]["PartyCode"];
            proposalType?: components["schemas"]["ProposalType"];
            documentTitle?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        VoteListResponse: {
            data: components["schemas"]["Vote"][];
            total: number;
            page: number;
            pageSize: number;
        };
        VoteDetail: {
            beteckning: string;
            forslagspunkt: string;
            dokId?: string;
            documentTitle: string;
            proposedByParty?: components["schemas"]["PartyCode"];
            proposalType?: components["schemas"]["ProposalType"];
            session?: string;
            partyBreakdown: components["schemas"]["PartyVotePosition"][];
            /** @description AI-generated explanation of political context */
            contextNote?: string;
            /** @description Decision date from Riksdagen, YYYY-MM-DD */
            date?: string;
            /** @description Authoritative outcome: Bifall | Avslag | Återremiss */
            status?: string;
            subtitle?: string;
            /** @description Plain-text summary of the betänkande */
            summary?: string;
        };
        PartyVotePosition: {
            party: components["schemas"]["PartyCode"];
            jaCount: number;
            nejCount: number;
            avstarCount: number;
            franvarandeCount: number;
            dominantVote?: components["schemas"]["VoteResult"];
        };
        Goal: {
            id: number;
            party: components["schemas"]["PartyCode"];
            goalText: string;
            topic: components["schemas"]["Topic"];
            specificity: components["schemas"]["Specificity"];
            /** @example Valmanifest 2022 */
            sourceDocument: string;
            /**
             * @description Live URL to the party's published source document for this goal.
             * @example https://moderaterna.se/.../valmanifest_2022.pdf
             */
            sourceUrl?: string;
            /** @description Verbatim excerpt from the source document the goal is derived from. */
            sourceQuote?: string;
            keywords?: string[];
            relevantCommittees?: string[];
        };
        GoalWithAlignment: components["schemas"]["Goal"] & {
            /** @description Vote points matched to this goal — a fact about our matching. The alignment percentage was retired: it systematically disadvantaged opposition parties, scoring a party that voted Nej to the rejection of its own motion as breaking its own promise. */
            relevantVotes?: number;
        };
        GoalVoteBreakdown: {
            goal: components["schemas"]["GoalWithAlignment"];
            matches: components["schemas"]["GoalVoteMatch"][];
        };
        GoalVoteMatch: {
            beteckning: string;
            forslagspunkt: string;
            /** Format: float */
            relevanceScore: number;
            alignedDirection: components["schemas"]["VoteResult"];
            explanation?: string;
            proposedByParty?: components["schemas"]["PartyCode"];
            proposalType?: components["schemas"]["ProposalType"];
            contextNote?: string;
            documentTitle?: string;
            /**
             * Format: float
             * @description What % of party members voted in the aligned direction
             */
            partyAlignmentPct?: number;
        };
        RecordCoverage: {
            mandate: components["schemas"]["MandatePeriod"];
            /** @description Riksdagen's count of voteringar in the mandate period. */
            expected: number;
            /** @description How many of those the site holds. */
            ingested: number;
            /** @description Voteringar Riksdagen lists that carry no beteckning and therefore cannot be fetched. Reported so a shortfall is explained rather than left as an unexplained gap. */
            unreachable: number;
            /** @description Date of the newest decision held. Not an ingest timestamp. */
            lastDecisionDate?: string | null;
            /** @description When `expected` was last read from Riksdagen — the oldest such date across the period's riksmöten, since the figure is only as fresh as its stalest part. `ingested` is counted live and always current; `expected`, `unreachable` and `lastDecisionDate` come from a separate enumeration pass, so their age is stated rather than implied. Null means the denominator has never been established. */
            denominatorCheckedAt?: string | null;
            byRiksmote: components["schemas"]["RiksmoteRecord"][];
        };
        MandatePeriod: {
            code: string;
            label: string;
            /** @description Whether the period has closed. Once it has, the record is final and the incoming parliament accumulates a separate one. */
            ended: boolean;
        };
        RiksmoteRecord: {
            riksmote: string;
            expected: number;
            ingested: number;
            unreachable: number;
            lastDecisionDate?: string | null;
            /** @description When this riksmöte's `expected` was last read from Riksdagen. */
            denominatorCheckedAt?: string | null;
        };
        PartySummary: {
            party: components["schemas"]["PartyCode"];
            totalGoals: number;
            topicBreakdown?: components["schemas"]["TopicAlignment"][];
        };
        TopicAlignment: {
            topic: components["schemas"]["Topic"];
            /** @description All goals in this topic, including unscorable ones. */
            goalCount: number;
        };
        Promise: {
            id: number;
            politicianId: string;
            speechId?: number;
            /** Format: date */
            speechDate?: string;
            speechTopic?: string;
            promiseText: string;
            topic: components["schemas"]["Topic"];
            specificity: components["schemas"]["Specificity"];
            keywords?: string[];
        };
        PromiseWithMatches: components["schemas"]["Promise"] & {
            voteMatches?: components["schemas"]["PromiseVoteMatch"][];
        };
        PromiseVoteMatch: {
            voteId: number;
            beteckning?: string;
            forslagspunkt?: string;
            documentTitle?: string;
            voteResult?: components["schemas"]["VoteResult"];
            /** Format: float */
            relevanceScore: number;
            /** @enum {string} */
            alignment: "supports" | "contradicts" | "unclear";
            explanation?: string;
            proposedByParty?: components["schemas"]["PartyCode"];
            proposalType?: components["schemas"]["ProposalType"];
        };
        ExpenditureArea: {
            /** @example UO6 */
            code: string;
            /** @example Försvar och samhällets krisberedskap */
            name: string;
            description?: string;
            sortOrder: number;
        };
        BudgetYear: {
            /** @example 2025 */
            year: number;
            /** @enum {string} */
            status: "decided" | "proposed";
            /**
             * Format: int64
             * @description Total budget in thousands of kronor
             */
            totalKsek: number;
        };
        BudgetAllocation: {
            area: components["schemas"]["ExpenditureArea"];
            /** Format: int64 */
            amountKsek: number;
            /** @description Human-readable amount, e.g. '145,2 mdkr' */
            amountFormatted?: string;
        };
        BudgetDocumentRef: {
            /**
             * @description Document type
             * @enum {string}
             */
            type: "proposition" | "committee_report";
            /** @example Prop. 2024/25:1 */
            title: string;
            /**
             * Format: uri
             * @description Link to the document on riksdagen.se
             */
            url: string;
            /** @example Budgetpropositionen för 2025 */
            description: string;
        };
        BudgetYearDetail: {
            year: number;
            /** @enum {string} */
            status: "decided" | "proposed";
            /** Format: int64 */
            totalKsek: number;
            allocations: components["schemas"]["BudgetAllocation"][];
            /** @description Links to relevant budget proposition and committee reports */
            documents?: components["schemas"]["BudgetDocumentRef"][];
        };
        BudgetComparisonRow: {
            area: components["schemas"]["ExpenditureArea"];
            /** Format: int64 */
            baseAmountKsek: number;
            /** Format: int64 */
            compareAmountKsek: number;
            /**
             * Format: int64
             * @description compareAmount - baseAmount
             */
            deltaKsek: number;
            /**
             * Format: float
             * @description Percentage change from base to compare year
             */
            deltaPct: number;
        };
        BudgetComparison: {
            baseYear: number;
            compareYear: number;
            /** Format: int64 */
            baseTotalKsek: number;
            /** Format: int64 */
            compareTotalKsek: number;
            /** Format: int64 */
            totalDeltaKsek?: number;
            /** Format: float */
            totalDeltaPct?: number;
            rows: components["schemas"]["BudgetComparisonRow"][];
        };
        AreaTimeSeries: {
            area: components["schemas"]["ExpenditureArea"];
            entries: components["schemas"]["AreaTimeSeriesEntry"][];
        };
        AreaTimeSeriesEntry: {
            year: number;
            /** Format: int64 */
            amountKsek: number;
            /** @description Links to the area-specific budget proposition volume */
            documents?: components["schemas"]["BudgetDocumentRef"][];
        };
        BudgetTrendEntry: {
            year: number;
            /** Format: int64 */
            amountKsek: number;
            /** @description Human-readable amount, e.g. '87,3 mdkr' */
            amountFormatted: string;
        };
        RelatedBudgetArea: {
            /** @example UO9 */
            code: string;
            name: string;
            trend: components["schemas"]["BudgetTrendEntry"][];
            /**
             * Format: float
             * @description Year-over-year change in percent
             */
            latestDeltaPct: number;
            /**
             * Format: float
             * @description Area's share of total national budget in the latest year
             */
            shareOfBudgetPct: number;
        };
        FundingRow: {
            code: string;
            name: string;
            /** Format: int64 */
            deltaKsek: number;
            /** Format: float */
            deltaPct: number;
        };
        FundingContext: {
            year: number;
            topIncreases: components["schemas"]["FundingRow"][];
            topDecreases: components["schemas"]["FundingRow"][];
            /** Format: int64 */
            totalBudgetDeltaKsek?: number;
            /** Format: float */
            totalBudgetDeltaPct?: number;
        };
        TopicContext: {
            topic: components["schemas"]["Topic"];
            description: string;
            committees: string[];
            relatedAreas: components["schemas"]["RelatedBudgetArea"][];
            fundingContext?: components["schemas"]["FundingContext"];
        };
        ElectionResult: {
            /** @description Party abbreviation (e.g. S, M, SD) or "OTHER" for small parties */
            party: string;
            /** @description Number of seats won */
            mandates: number;
            /**
             * Format: float
             * @description Share of votes in percent
             */
            votePct: number;
            /** @description Total seats in the assembly */
            totalMandates: number;
        };
        RegionSummary: {
            /**
             * @description Two-digit SCB region code
             * @example 01
             */
            code: string;
            /** @example Region Stockholm */
            name: string;
            /** @example Stockholm */
            capital: string;
            /** @example 2400000 */
            population: number;
            /** @example 2022 */
            electionYear: number;
            /** @description Parties in the governing coalition */
            governingParties: string[];
            /** @description Total seats in regionfullmäktige */
            totalMandates: number;
        };
        RegionDetail: components["schemas"]["RegionSummary"] & {
            electionResults: components["schemas"]["ElectionResult"][];
        };
        RegionPlanGoal: {
            /**
             * @description Goal exactly as the plan prints it (verbatim, region's wording)
             * @example Kollektivtrafiken är tillgänglig och attraktiv
             */
            title: string;
            /**
             * @description Optional verbatim clarifying line (e.g. perspektiv/målområde)
             * @example Perspektiv: Invånare
             */
            description?: string;
        };
        RegionPlan: {
            /** @example 01 */
            code: string;
            /**
             * @description What the region calls its annual-plan document
             * @example Budget för Region Stockholm
             */
            label: string;
            /**
             * @description Official page or document on the region's own domain
             * @example https://www.regionstockholm.se/om-region-stockholm/ekonomi-och-budget/budget/
             */
            url: string;
            /**
             * @description What the region calls these goals (e.g. Effektmål, Målområden)
             * @example Mål i budget
             */
            goalsLabel?: string;
            /**
             * @description Plan period the goals are taken from
             * @example 2026
             */
            period?: string;
            /** @description Region's own overarching goals, verbatim and complete (empty for link-only) */
            goals: components["schemas"]["RegionPlanGoal"][];
        };
        RiksdagFeedItem: {
            /** @example 2025-04-15 */
            time: string;
            /** @example Betänkande om sjukvårdsreform */
            title: string;
            /** @example Bifall */
            status: string;
            /** @example Vård */
            tag?: string;
            /** @example SoU2425:12 */
            beteckning?: string;
        };
        RiksdagDocument: {
            dokId: string;
            /** @description Riksdagen document type (bet, ip, mot, prop, etc.) */
            type: string;
            title: string;
            subtitle?: string;
            summary?: string;
            date?: string;
            /** @description Present for betänkanden and motions */
            beteckning?: string;
        };
        Intressent: {
            intressentId: string;
            name: string;
            /** @description Party abbreviation from Riksdagen API (may be outside the PartyCode enum for historical parties, e.g. FP) */
            party: string;
            /** @description Role in this document (e.g. "Upphovsman", "Svar") */
            role?: string;
        };
        RiksdagDocumentFull: components["schemas"]["RiksdagDocument"] & {
            /** @description Full document body from riksdagen dokumentstatus HTML field */
            bodyHtml?: string;
            intressenter: components["schemas"]["Intressent"][];
        };
        RegionBudgetArea: {
            /** @example Primärvård */
            name: string;
            /**
             * Format: float
             * @description Net cost in mnkr (miljoner kronor)
             * @example 2654
             */
            value: number;
            /**
             * Format: float
             * @description Share of total regional nettokostnad
             * @example 18.9
             */
            pct: number;
        };
        RegionBudgetSnapshot: {
            region_code: string;
            area_name: string;
            year: number;
            value_mnkr: number;
            total_mnkr: number;
            pct: number;
        };
        MunicipalityBudgetSnapshot: {
            mun_code: string;
            area_name: string;
            year: number;
            value_mnkr: number;
            total_mnkr: number;
            pct: number;
        };
        RegionAreaDataPoint: {
            region_code: string;
            value_mnkr: number;
            total_mnkr: number;
            pct: number;
        };
        MunicipalitySummary: {
            /**
             * @description Four-digit SCB municipality code
             * @example 0180
             */
            code: string;
            /** @example Stockholms kommun */
            name: string;
            /** @example 01 */
            regionCode: string;
            /** @example Region Stockholm */
            regionName: string;
            /** @example 980000 */
            population: number;
            /** @example 2022 */
            electionYear: number;
            /** @description Parties in the governing coalition */
            governingParties: string[];
            /** @description Total seats in kommunfullmäktige */
            totalMandates: number;
        };
        MunicipalityDetail: components["schemas"]["MunicipalitySummary"] & {
            electionResults: components["schemas"]["ElectionResult"][];
        };
        MunicipalityKPIItem: {
            /**
             * @description Kolada KPI code
             * @example N00902
             */
            kpi: string;
            /** @example 2023 */
            year: number;
            /**
             * Format: float
             * @example 85432
             */
            value: number;
            /**
             * @description Empty string means normal; "M" means missing data
             * @example
             */
            status: string;
        };
        RegionKPIRankEntry: {
            /** @example 09 */
            region_code: string;
            /** @example Blekinge */
            name: string;
            /**
             * Format: float
             * @example 41200.5
             */
            value: number;
            /** @example 2023 */
            year: number;
            /** @example 5 */
            rank: number;
            /** @example 21 */
            total: number;
        };
        KPIRankEntry: {
            /** @example 0180 */
            mun_code: string;
            /** @example Stockholm */
            name: string;
            /**
             * Format: float
             * @example 22.85
             */
            value: number;
            /** @example 2023 */
            year: number;
            /** @example 47 */
            rank: number;
            /** @example 290 */
            total: number;
        };
        KPIRank: {
            /** @example N00900 */
            kpi: string;
            /** @example 47 */
            rank: number;
            /** @example 290 */
            total: number;
            /**
             * Format: float
             * @example 22.14
             */
            mean: number;
        };
        PopulationTrendEntry: {
            /** @example 2023 */
            year: number;
            /** @example 978770 */
            population: number;
        };
        ProcurementCategorySummary: {
            /**
             * @description First two digits of the CPV code (main division)
             * @example 45
             */
            cpv_division: string;
            /**
             * @description Swedish label for the CPV division
             * @example Bygg & anläggning
             */
            label: string;
            /**
             * Format: float
             * @description Total contracted value in SEK for this category
             * @example 1105500000
             */
            total_value_sek: number;
            /**
             * Format: float
             * @description Percentage of total procurement spend
             * @example 27.1
             */
            pct: number;
            /**
             * @description Number of contract award notices in this category
             * @example 12
             */
            count: number;
        };
        YearlyExpenditure: {
            /** @example 2024 */
            year: number;
            /**
             * Format: float
             * @example 41.4
             */
            expenditureMdkr: number;
        };
        RegisteredAuthority: {
            /** @example 202100-0076 */
            orgNumber: string;
            /** @example polismyndigheten */
            slug: string;
            /** @example POLISMYNDIGHETEN */
            name: string;
            /** @enum {string} */
            type: "Förvaltningsmyndighet" | "Riksdagsmyndighet" | "Affärsverk" | "AP-fond" | "Domstol" | "Utlandsmyndighet";
            /** @enum {string} */
            principalBody: "Regeringen" | "Riksdagen";
            /** @example Justitiedepartementet */
            department: string;
            underGovernment: boolean;
            website?: string;
            sfs?: string;
            expenditureMdkr?: number | null;
            budgetMdkr?: number | null;
            headcountInt?: number | null;
            year: number;
            /** Format: date-time */
            updatedAt?: string;
        };
        AuthorityStats: {
            total: number;
            underGovernment: number;
            withExpenditure: number;
            withHeadcount: number;
            totalExpenditureMdkr: number;
            totalHeadcount: number;
            /** Format: date-time */
            latestUpdatedAt: string;
        };
        RegisteredAuthorityList: {
            items: components["schemas"]["RegisteredAuthority"][];
            total: number;
            page: number;
            pageSize: number;
        };
        RiksdagAuthority: {
            /** @example polismyndigheten */
            slug: string;
            /** @example Polismyndigheten */
            name: string;
            /** @example Ordning & utredning */
            role: string;
            /** @example Justitiedepartementet */
            ministry: string;
            /** @example 35 500 */
            headcount: string;
            /** @example 35500 */
            headcountInt: number;
            /** @example Sveriges största myndighet, ansvarar för brottsbekämpning, utredning och ordningshållning. */
            description?: string;
            /**
             * Format: uri
             * @example https://polisen.se
             */
            websiteUrl?: string;
            /**
             * Format: uri
             * @example https://polisen.se/om-polisen/organisation/arsredovisning/
             */
            annualReportUrl?: string;
            /**
             * Format: float
             * @description Actual annual driftkostnad in mdkr (excl. transfer payments)
             * @example 41.4
             */
            expenditureMdkr: number;
            /** @example 2024 */
            year: number;
            history?: components["schemas"]["YearlyExpenditure"][];
        };
        AgencyRegleringsbrev: {
            /** @example 2024 */
            year: number;
            /**
             * Format: date
             * @example 2024-12-19
             */
            date: string;
            /** @example Regleringsbrev för budgetåret 2024 avseende Polismyndigheten */
            title: string;
            /** @example Polismyndigheten ska verka för att minska brottsligheten och öka tryggheten. */
            summary: string;
            /**
             * Format: uri
             * @example https://www.riksdagen.se/sv/dokument-och-lagar/dokument/Rb12345/
             */
            url: string;
        };
        AgencyDecision: {
            /**
             * Format: date
             * @example 2024-11-20
             */
            date: string;
            /** @example Riksdagens kontrollmakt och Riksrevisionen */
            title: string;
            /** @example bet */
            docType: string;
            summary: string;
            /** Format: uri */
            url: string;
        };
        RiksdagAuthorityDetail: components["schemas"]["RiksdagAuthority"] & {
            /** @example Inrättades 2015 per polislagen. Nationell civil myndighet med ansvar för brottsförebyggande arbete, utredning och ordningshållning. */
            mandate: string;
            /**
             * Format: uri
             * @example https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/polislag-1984387_sfs-1984-387/
             */
            mandateUrl?: string;
            regleringsbrev: components["schemas"]["AgencyRegleringsbrev"][];
            recentDecisions: components["schemas"]["AgencyDecision"][];
        };
        Speech: {
            id: number;
            dokId: string;
            anforandeNummer?: string;
            politicianId: string;
            politicianName: string;
            /** @description URL to politician portrait (Riksdagen CDN). May be empty. */
            politicianImageUrl?: string;
            party: string;
            /** Format: date-time */
            date: string;
            topicHeading?: string;
            snippet: string;
            /** @description Full text — only included on /speeches/{id}, omitted from /speeches/recent */
            speechText?: string;
            /** @description Dok ID of the related document (interpellation, betänkande, etc.) */
            relatedDokId?: string;
        };
        /** @description One whole government document, not a point extracted from one. Carries no description and no status: a description would be our paraphrase of the document's words, and a status ('active', 'in_progress') would be our unsourced claim about how the government is progressing. The list of documents is ours — a missing document means we have not registered it, never that it does not exist. */
        RiksdagAgendaItem: {
            id: number;
            title: string;
            /** @description The document's short designation, e.g. "Prop. 2025/26:1". */
            source: string;
            /** @description Who published it — a ministry, or the parties to an agreement. */
            issuer: string;
            /** @description Link to the document itself, in full. */
            url: string;
            /** @description Publication date as YYYY-MM-DD, null when we hold none. */
            published?: string | null;
        };
        Party: {
            code?: string;
            name?: string;
            foundedYear?: number | null;
            ideology?: string | null;
            colorHex?: string;
            textHex?: string;
            active?: boolean;
            websiteUrl?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        Minister: {
            id?: string;
            name?: string;
            title?: string;
            department?: string;
            departmentCode?: string;
            party?: string;
            politicianId?: string | null;
            photoUrl?: string | null;
            bio?: string | null;
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        Proposal: {
            id?: string;
            title?: string;
            departmentCode?: string;
            riksdagYear?: string;
            /** Format: date-time */
            publishedAt?: string | null;
            url?: string;
        };
        DepartmentGroup: {
            department?: string;
            departmentCode?: string;
            ministers?: components["schemas"]["Minister"][];
        };
        MinisterDetail: {
            minister?: components["schemas"]["Minister"];
            proposals?: components["schemas"]["Proposal"][];
        };
        Committee: {
            /** @description Canonical committee code, e.g. "SoU". ALL-CAPS vintages are normalised. */
            code: string;
            /** @description Swedish name, or the code itself when we have no name for it. The lookup is a display aid and never a gate on what the record contains. */
            name: string;
            /** @description How many voteringar the committee decided in the period, counted as the record itself identifies a votering (one votering_id). A förslagspunkt decided by two voteringar therefore counts twice, because the record holds two. A count of the record, not a measure of importance — never presented as a ranking. */
            voteringar: number;
            /** @description Utgiftsområden the committee bereder, per the Bilaga to riksdagsordningen. Amounts only, never a share of the total: a share would understate a committee whose remit exceeds its areas. Populated only by GET /committees/{code}; the list endpoint returns it empty rather than issuing one query per committee. */
            expenditureAreas: components["schemas"]["CommitteeExpenditureArea"][];
        };
        CommitteeExpenditureArea: {
            code: string;
            name: string;
            /** Format: int64 */
            amountKsek: number;
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Invalid request parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        PartyParam: components["schemas"]["PartyCode"];
        PoliticianIdParam: string;
        BudgetYearParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRiksdagAuthorities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of state agencies sorted by expenditure descending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiksdagAuthority"][];
                };
            };
            /** @description Upstream data source unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRiksdagAuthorityStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorityStats"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRiksdagMyndigheter: {
        parameters: {
            query?: {
                /** @description Free-text name match (ILIKE) */
                q?: string;
                /** @description Filter to agencies under the Government (true) or not (false) */
                underGovernment?: "true" | "false";
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredAuthorityList"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRiksdagAuthority: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example polismyndigheten */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agency detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiksdagAuthorityDetail"];
                };
            };
            /** @description Agency not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upstream data source unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPartyMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Party"][];
                };
            };
        };
    };
    getPartyMeta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Party"];
                };
            };
            /** @description Party not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMinisters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentGroup"][];
                };
            };
        };
    };
    getMinister: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MinisterDetail"];
                };
            };
            /** @description Minister not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listParties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of parties with aggregate alignment scores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartySummary"][];
                };
            };
        };
    };
    listPartyGoals: {
        parameters: {
            query?: {
                topic?: components["schemas"]["Topic"];
            };
            header?: never;
            path: {
                party: components["parameters"]["PartyParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Party goals with vote alignment data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalWithAlignment"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listGoalVotes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party: components["parameters"]["PartyParam"];
                goalId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Votes relevant to this goal with context notes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalVoteBreakdown"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPoliticians: {
        parameters: {
            query?: {
                party?: components["schemas"]["PartyCode"];
                active?: boolean;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of politicians */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoliticianListResponse"];
                };
            };
        };
    };
    getPolitician: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PoliticianIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Politician profile with statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoliticianProfile"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPoliticianPromises: {
        parameters: {
            query?: {
                topic?: components["schemas"]["Topic"];
            };
            header?: never;
            path: {
                id: components["parameters"]["PoliticianIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Promises with vote alignment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromiseWithMatches"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPoliticianVotes: {
        parameters: {
            query?: {
                session?: string;
                topic?: components["schemas"]["Topic"];
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["PoliticianIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Voting record with proposal origin */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getRiksdagFeed: {
        parameters: {
            query: {
                level: "region" | "kommun";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent betänkanden with beteckning for deep-linking */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiksdagFeedItem"][];
                };
            };
        };
    };
    getVoteDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                beteckning: string;
                punkt: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full vote detail with party breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getDocumentFull: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dokId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full document with body and participants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiksdagDocumentFull"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dokId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Parsed dokumentstatus metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiksdagDocument"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listBudgetYears: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Budget years with total amounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetYear"][];
                };
            };
        };
    };
    getBudgetYear: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: components["parameters"]["BudgetYearParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Budget year with all expenditure area allocations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetYearDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    compareBudgetYears: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: components["parameters"]["BudgetYearParam"];
                compareYear: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comparison with delta amounts and percentages per area */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetComparison"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listExpenditureAreas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expenditure areas ordered by sort_order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenditureArea"][];
                };
            };
        };
    };
    getTopicContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic: components["schemas"]["Topic"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Topic context with budget trend and funding analysis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicContext"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAreaTimeSeries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Yearly amounts for the expenditure area */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaTimeSeries"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRegions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All regions with 2022 election summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionSummary"][];
                };
            };
        };
    };
    getRegionKPIRanking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kpiCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of rank entries sorted by value descending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionKPIRankEntry"][];
                };
            };
            /** @description Upstream Kolada API error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRegionKPIRanks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of KPI rank entries (one per region strip KPI) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KPIRank"][];
                };
            };
            /** @description Upstream Kolada API error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRegion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Region with full election result breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getRegionPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan document link plus the region's verbatim overarching goals (goals may be empty for link-only regions) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionPlan"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getRegionBudget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Budget areas with value in mnkr and percentage of total */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionBudgetArea"][];
                };
            };
            /** @description Upstream SCB API error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRegionBudgetHistory: {
        parameters: {
            query?: {
                years?: number;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of budget snapshots across years */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionBudgetSnapshot"][];
                };
            };
        };
    };
    getRegionAreaAcrossRegions: {
        parameters: {
            query?: {
                year?: number;
            };
            header?: never;
            path: {
                areaName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of data points, one per region */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionAreaDataPoint"][];
                };
            };
        };
    };
    listMunicipalities: {
        parameters: {
            query?: {
                regionCode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Municipalities with election summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MunicipalitySummary"][];
                };
            };
        };
    };
    getMunicipalityKPIRanking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kpiCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of rank entries sorted by value descending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KPIRankEntry"][];
                };
            };
            /** @description Upstream Kolada API error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMunicipalityKPIRanks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of KPI rank entries (one per default KPI) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KPIRank"][];
                };
            };
            /** @description Upstream Kolada API error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMunicipality: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Municipality with full election result breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MunicipalityDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMunicipalityKPIs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of KPI values (up to 2 years per indicator) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MunicipalityKPIItem"][];
                };
            };
            /** @description Upstream Kolada API error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMunicipalitySpending: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 0180 */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of spending KPI values (8 sectors × up to 5 years) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MunicipalityKPIItem"][];
                };
            };
            /** @description Upstream Kolada API error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMunicipalityBudgetHistory: {
        parameters: {
            query?: {
                years?: number;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of budget snapshots across years */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MunicipalityBudgetSnapshot"][];
                };
            };
        };
    };
    getMunicipalityProcurement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 1480 */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Top CPV procurement categories by contracted value */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcurementCategorySummary"][];
                };
            };
            /** @description Upstream TED API error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMunicipalityPopulationTrend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Year-by-year population entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PopulationTrendEntry"][];
                };
            };
            /** @description Upstream SCB API error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCommittees: {
        parameters: {
            query: {
                /** @description Mandate period code, e.g. "2022-2026". */
                period: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Committees, alphabetical by code. expenditureAreas is empty here — only GET /committees/{code} populates it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Committee"][];
                };
            };
            /** @description No such mandate period. A period we do not hold is refused rather than answered with an empty list, which would read as "this parliament decided nothing". */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCommittee: {
        parameters: {
            query: {
                period: string;
                /** @description Budget year for the amounts. Defaults to the newest year with decided figures. A year without decided figures is a 400, never a 200 carrying zero amounts. */
                year?: number;
            };
            header?: never;
            path: {
                /** @description Committee code, matched case-insensitively — "fiu" and "FiU" are the same committee. */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The committee, with the utgiftsområden it bereder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Committee"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description No such mandate period, or that committee decided nothing in it */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
