/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all parties with summary scorecard data */
        get: operations["listParties"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties/{party}/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all goals for a party with alignment percentages */
        get: operations["listPartyGoals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties/{party}/goals/{goalId}/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detailed vote breakdown for a specific party goal */
        get: operations["listGoalVotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/politicians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List politicians with summary statistics */
        get: operations["listPoliticians"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/politicians/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full politician profile */
        get: operations["getPolitician"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/politicians/{id}/promises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Promises extracted from speeches with vote match results */
        get: operations["listPoliticianPromises"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/politicians/{id}/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Voting record with proposal origin context */
        get: operations["listPoliticianVotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/votes/{beteckning}/{punkt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full vote detail with proposal origin and all party positions */
        get: operations["getVoteDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all available budget years with totals */
        get: operations["listBudgetYears"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/years/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full budget breakdown for a specific year */
        get: operations["getBudgetYear"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/years/{year}/compare/{compareYear}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Side-by-side comparison of two budget years with deltas */
        get: operations["compareBudgetYears"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all 27 expenditure areas */
        get: operations["listExpenditureAreas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/context/topic/{topic}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Budget and economic context for a political topic */
        get: operations["getTopicContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget/areas/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time series of budget amounts for one expenditure area */
        get: operations["getAreaTimeSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all 21 Swedish regions with election results and governing parties */
        get: operations["listRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full region detail including election results per party */
        get: operations["getRegion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/municipalities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Swedish municipalities, optionally filtered by region */
        get: operations["listMunicipalities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/municipalities/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full municipality detail including election results per party */
        get: operations["getMunicipality"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/municipalities/{code}/kpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kolada KPI spending metrics for a municipality */
        get: operations["getMunicipalityKPIs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/municipalities/{code}/spending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sector spending breakdown from Kolada (2019–2023) */
        get: operations["getMunicipalitySpending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/municipalities/{code}/procurement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public procurement breakdown by CPV category from TED (2021–2024) */
        get: operations["getMunicipalityProcurement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/municipalities/{code}/population-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SCB population trend for a municipality (2019–2023) */
        get: operations["getMunicipalityPopulationTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            version?: string;
        };
        ErrorResponse: {
            error: string;
            detail?: string;
        };
        /**
         * @description Swedish party abbreviation
         * @enum {string}
         */
        PartyCode: "S" | "M" | "SD" | "C" | "V" | "KD" | "L" | "MP" | "unknown";
        /** @enum {string} */
        Topic: "sjukvard" | "forsvar" | "invandring" | "skatt" | "skola" | "klimat" | "brott" | "bostad" | "arbete" | "energi" | "other";
        /** @enum {string} */
        VoteResult: "Ja" | "Nej" | "Avstår" | "Frånvarande";
        /**
         * @description prop=government bill, mot=party motion, bet=committee report
         * @enum {string}
         */
        ProposalType: "prop" | "mot" | "bet";
        /** @enum {string} */
        Specificity: "concrete" | "directional" | "rhetorical";
        Politician: {
            intressentId: string;
            firstName: string;
            lastName: string;
            party: components["schemas"]["PartyCode"];
            constituency?: string;
            /** Format: uri */
            imageUrl?: string;
            isActive: boolean;
        };
        PoliticianSummary: components["schemas"]["Politician"] & {
            totalVotes?: number;
            promiseCount?: number;
            /**
             * Format: float
             * @description Overall promise-to-vote alignment percentage
             */
            alignmentPct?: number;
        };
        PoliticianProfile: components["schemas"]["PoliticianSummary"] & {
            recentSpeeches?: components["schemas"]["SpeechSummary"][];
        };
        PoliticianListResponse: {
            data: components["schemas"]["PoliticianSummary"][];
            total: number;
            page: number;
            pageSize: number;
        };
        SpeechSummary: {
            id: number;
            dokId?: string;
            /** Format: date */
            date: string;
            topicHeading: string;
        };
        Vote: {
            id: number;
            voteringId: string;
            politicianId: string;
            party: components["schemas"]["PartyCode"];
            voteResult: components["schemas"]["VoteResult"];
            /** @description Committee report ID e.g. SoU12 */
            beteckning: string;
            forslagspunkt: string;
            /** @example 2024/25 */
            session: string;
            dokId?: string;
            proposedByParty?: components["schemas"]["PartyCode"];
            proposalType?: components["schemas"]["ProposalType"];
            documentTitle?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        VoteListResponse: {
            data: components["schemas"]["Vote"][];
            total: number;
            page: number;
            pageSize: number;
        };
        VoteDetail: {
            beteckning: string;
            forslagspunkt: string;
            dokId?: string;
            documentTitle: string;
            proposedByParty?: components["schemas"]["PartyCode"];
            proposalType?: components["schemas"]["ProposalType"];
            session?: string;
            partyBreakdown: components["schemas"]["PartyVotePosition"][];
            /** @description AI-generated explanation of political context */
            contextNote?: string;
        };
        PartyVotePosition: {
            party: components["schemas"]["PartyCode"];
            jaCount: number;
            nejCount: number;
            avstarCount: number;
            franvarandeCount: number;
            dominantVote?: components["schemas"]["VoteResult"];
        };
        Goal: {
            id: number;
            party: components["schemas"]["PartyCode"];
            goalText: string;
            topic: components["schemas"]["Topic"];
            specificity: components["schemas"]["Specificity"];
            /** @example Valmanifest 2022 */
            sourceDocument: string;
            keywords?: string[];
            relevantCommittees?: string[];
        };
        GoalWithAlignment: components["schemas"]["Goal"] & {
            relevantVotes?: number;
            /**
             * Format: float
             * @description Percentage of relevant votes aligned with goal direction
             */
            alignmentPct?: number;
        };
        GoalVoteBreakdown: {
            goal: components["schemas"]["GoalWithAlignment"];
            matches: components["schemas"]["GoalVoteMatch"][];
        };
        GoalVoteMatch: {
            beteckning: string;
            forslagspunkt: string;
            /** Format: float */
            relevanceScore: number;
            alignedDirection: components["schemas"]["VoteResult"];
            explanation?: string;
            proposedByParty?: components["schemas"]["PartyCode"];
            proposalType?: components["schemas"]["ProposalType"];
            contextNote?: string;
            documentTitle?: string;
            /**
             * Format: float
             * @description What % of party members voted in the aligned direction
             */
            partyAlignmentPct?: number;
        };
        PartySummary: {
            party: components["schemas"]["PartyCode"];
            totalGoals: number;
            /** Format: float */
            avgAlignmentPct: number;
            topicBreakdown?: components["schemas"]["TopicAlignment"][];
        };
        TopicAlignment: {
            topic: components["schemas"]["Topic"];
            goalCount: number;
            /** Format: float */
            alignmentPct: number;
        };
        Promise: {
            id: number;
            politicianId: string;
            speechId?: number;
            /** Format: date */
            speechDate?: string;
            speechTopic?: string;
            promiseText: string;
            topic: components["schemas"]["Topic"];
            specificity: components["schemas"]["Specificity"];
            keywords?: string[];
        };
        PromiseWithMatches: components["schemas"]["Promise"] & {
            voteMatches?: components["schemas"]["PromiseVoteMatch"][];
        };
        PromiseVoteMatch: {
            voteId: number;
            beteckning?: string;
            forslagspunkt?: string;
            documentTitle?: string;
            voteResult?: components["schemas"]["VoteResult"];
            /** Format: float */
            relevanceScore: number;
            /** @enum {string} */
            alignment: "supports" | "contradicts" | "unclear";
            explanation?: string;
            proposedByParty?: components["schemas"]["PartyCode"];
            proposalType?: components["schemas"]["ProposalType"];
        };
        ExpenditureArea: {
            /** @example UO6 */
            code: string;
            /** @example Försvar och samhällets krisberedskap */
            name: string;
            description?: string;
            sortOrder: number;
        };
        BudgetYear: {
            /** @example 2025 */
            year: number;
            /** @enum {string} */
            status: "decided" | "proposed";
            /**
             * Format: int64
             * @description Total budget in thousands of kronor
             */
            totalKsek: number;
        };
        BudgetAllocation: {
            area: components["schemas"]["ExpenditureArea"];
            /** Format: int64 */
            amountKsek: number;
            /** @description Human-readable amount, e.g. '145,2 mdkr' */
            amountFormatted?: string;
        };
        BudgetDocumentRef: {
            /**
             * @description Document type
             * @enum {string}
             */
            type: "proposition" | "committee_report";
            /** @example Prop. 2024/25:1 */
            title: string;
            /**
             * Format: uri
             * @description Link to the document on riksdagen.se
             */
            url: string;
            /** @example Budgetpropositionen för 2025 */
            description: string;
        };
        BudgetYearDetail: {
            year: number;
            /** @enum {string} */
            status: "decided" | "proposed";
            /** Format: int64 */
            totalKsek: number;
            allocations: components["schemas"]["BudgetAllocation"][];
            /** @description Links to relevant budget proposition and committee reports */
            documents?: components["schemas"]["BudgetDocumentRef"][];
        };
        BudgetComparisonRow: {
            area: components["schemas"]["ExpenditureArea"];
            /** Format: int64 */
            baseAmountKsek: number;
            /** Format: int64 */
            compareAmountKsek: number;
            /**
             * Format: int64
             * @description compareAmount - baseAmount
             */
            deltaKsek: number;
            /**
             * Format: float
             * @description Percentage change from base to compare year
             */
            deltaPct: number;
        };
        BudgetComparison: {
            baseYear: number;
            compareYear: number;
            /** Format: int64 */
            baseTotalKsek: number;
            /** Format: int64 */
            compareTotalKsek: number;
            /** Format: int64 */
            totalDeltaKsek?: number;
            /** Format: float */
            totalDeltaPct?: number;
            rows: components["schemas"]["BudgetComparisonRow"][];
        };
        AreaTimeSeries: {
            area: components["schemas"]["ExpenditureArea"];
            entries: components["schemas"]["AreaTimeSeriesEntry"][];
        };
        AreaTimeSeriesEntry: {
            year: number;
            /** Format: int64 */
            amountKsek: number;
            /** @description Links to the area-specific budget proposition volume */
            documents?: components["schemas"]["BudgetDocumentRef"][];
        };
        BudgetTrendEntry: {
            year: number;
            /** Format: int64 */
            amountKsek: number;
            /** @description Human-readable amount, e.g. '87,3 mdkr' */
            amountFormatted: string;
        };
        RelatedBudgetArea: {
            /** @example UO9 */
            code: string;
            name: string;
            trend: components["schemas"]["BudgetTrendEntry"][];
            /**
             * Format: float
             * @description Year-over-year change in percent
             */
            latestDeltaPct: number;
            /**
             * Format: float
             * @description Area's share of total national budget in the latest year
             */
            shareOfBudgetPct: number;
        };
        FundingRow: {
            code: string;
            name: string;
            /** Format: int64 */
            deltaKsek: number;
            /** Format: float */
            deltaPct: number;
        };
        FundingContext: {
            year: number;
            topIncreases: components["schemas"]["FundingRow"][];
            topDecreases: components["schemas"]["FundingRow"][];
            /** Format: int64 */
            totalBudgetDeltaKsek?: number;
            /** Format: float */
            totalBudgetDeltaPct?: number;
        };
        TopicContext: {
            topic: components["schemas"]["Topic"];
            description: string;
            committees: string[];
            relatedAreas: components["schemas"]["RelatedBudgetArea"][];
            fundingContext?: components["schemas"]["FundingContext"];
        };
        ElectionResult: {
            /** @description Party abbreviation (e.g. S, M, SD) or "OTHER" for small parties */
            party: string;
            /** @description Number of seats won */
            mandates: number;
            /**
             * Format: float
             * @description Share of votes in percent
             */
            votePct: number;
            /** @description Total seats in the assembly */
            totalMandates: number;
        };
        RegionSummary: {
            /**
             * @description Two-digit SCB region code
             * @example 01
             */
            code: string;
            /** @example Region Stockholm */
            name: string;
            /** @example Stockholm */
            capital: string;
            /** @example 2400000 */
            population: number;
            /** @example 2022 */
            electionYear: number;
            /** @description Parties in the governing coalition */
            governingParties: string[];
            /** @description Total seats in regionfullmäktige */
            totalMandates: number;
        };
        RegionDetail: components["schemas"]["RegionSummary"] & {
            electionResults: components["schemas"]["ElectionResult"][];
        };
        MunicipalitySummary: {
            /**
             * @description Four-digit SCB municipality code
             * @example 0180
             */
            code: string;
            /** @example Stockholms kommun */
            name: string;
            /** @example 01 */
            regionCode: string;
            /** @example Region Stockholm */
            regionName: string;
            /** @example 980000 */
            population: number;
            /** @example 2022 */
            electionYear: number;
            /** @description Parties in the governing coalition */
            governingParties: string[];
            /** @description Total seats in kommunfullmäktige */
            totalMandates: number;
        };
        MunicipalityDetail: components["schemas"]["MunicipalitySummary"] & {
            electionResults: components["schemas"]["ElectionResult"][];
        };
        MunicipalityKPIItem: {
            /**
             * @description Kolada KPI code
             * @example N00902
             */
            kpi: string;
            /** @example 2023 */
            year: number;
            /**
             * Format: float
             * @example 85432
             */
            value: number;
            /**
             * @description Empty string means normal; "M" means missing data
             * @example
             */
            status: string;
        };
        PopulationTrendEntry: {
            /** @example 2023 */
            year: number;
            /** @example 978770 */
            population: number;
        };
        ProcurementCategorySummary: {
            /**
             * @description First two digits of the CPV code (main division)
             * @example 45
             */
            cpv_division: string;
            /**
             * @description Swedish label for the CPV division
             * @example Bygg & anläggning
             */
            label: string;
            /**
             * Format: float
             * @description Total contracted value in SEK for this category
             * @example 1105500000
             */
            total_value_sek: number;
            /**
             * Format: float
             * @description Percentage of total procurement spend
             * @example 27.1
             */
            pct: number;
            /**
             * @description Number of contract award notices in this category
             * @example 12
             */
            count: number;
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Invalid request parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        PartyParam: components["schemas"]["PartyCode"];
        PoliticianIdParam: string;
        BudgetYearParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listParties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of parties with aggregate alignment scores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartySummary"][];
                };
            };
        };
    };
    listPartyGoals: {
        parameters: {
            query?: {
                topic?: components["schemas"]["Topic"];
            };
            header?: never;
            path: {
                party: components["parameters"]["PartyParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Party goals with vote alignment data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalWithAlignment"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listGoalVotes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party: components["parameters"]["PartyParam"];
                goalId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Votes relevant to this goal with context notes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalVoteBreakdown"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPoliticians: {
        parameters: {
            query?: {
                party?: components["schemas"]["PartyCode"];
                active?: boolean;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of politicians */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoliticianListResponse"];
                };
            };
        };
    };
    getPolitician: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PoliticianIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Politician profile with statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoliticianProfile"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPoliticianPromises: {
        parameters: {
            query?: {
                topic?: components["schemas"]["Topic"];
            };
            header?: never;
            path: {
                id: components["parameters"]["PoliticianIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Promises with vote alignment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromiseWithMatches"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPoliticianVotes: {
        parameters: {
            query?: {
                session?: string;
                topic?: components["schemas"]["Topic"];
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["PoliticianIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Voting record with proposal origin */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getVoteDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                beteckning: string;
                punkt: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full vote detail with party breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listBudgetYears: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Budget years with total amounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetYear"][];
                };
            };
        };
    };
    getBudgetYear: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: components["parameters"]["BudgetYearParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Budget year with all expenditure area allocations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetYearDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    compareBudgetYears: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: components["parameters"]["BudgetYearParam"];
                compareYear: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comparison with delta amounts and percentages per area */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetComparison"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listExpenditureAreas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expenditure areas ordered by sort_order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenditureArea"][];
                };
            };
        };
    };
    getTopicContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic: components["schemas"]["Topic"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Topic context with budget trend and funding analysis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicContext"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAreaTimeSeries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Yearly amounts for the expenditure area */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaTimeSeries"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRegions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All regions with 2022 election summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionSummary"][];
                };
            };
        };
    };
    getRegion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Region with full election result breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listMunicipalities: {
        parameters: {
            query?: {
                regionCode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Municipalities with election summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MunicipalitySummary"][];
                };
            };
        };
    };
    getMunicipality: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Municipality with full election result breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MunicipalityDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMunicipalityKPIs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of KPI values (up to 2 years per indicator) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MunicipalityKPIItem"][];
                };
            };
            /** @description Upstream Kolada API error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMunicipalitySpending: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 0180 */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of spending KPI values (8 sectors × up to 5 years) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MunicipalityKPIItem"][];
                };
            };
            /** @description Upstream Kolada API error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMunicipalityProcurement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 1480 */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Top CPV procurement categories by contracted value */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcurementCategorySummary"][];
                };
            };
            /** @description Upstream TED API error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMunicipalityPopulationTrend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Year-by-year population entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PopulationTrendEntry"][];
                };
            };
            /** @description Upstream SCB API error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
