apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "riksdagskollen.fullname" . }}-backend
  labels:
    {{- include "riksdagskollen.labels" . | nindent 4 }}
    {{- include "riksdagskollen.backend.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "riksdagskollen.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "riksdagskollen.labels" . | nindent 8 }}
        {{- include "riksdagskollen.backend.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- if .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.backend.imagePullSecrets | nindent 8 }}
      {{- end }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
              protocol: TCP
          env:
            {{- range $k, $v := .Values.backend.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecretName }}
                  key: DATABASE_URL
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
